### ISSUE TITLE
Making a file in the data folder 

### ISSUE THREAD

**Issue by karimrida** [navidcy/KolmogorovFlow#7]
After creating the "data" and "movies" folder in the main directory and I run "setup_and_run_simulation.jl" file I am getting an error that the file "kolmogorovflow.jld2" is not found in the "data" folder. This the error that I got: 

```
ERROR: LoadError: LoadError: SystemError: opening file "./data/kolmogorovflow.jld2": No such file or directory
```

**Comment by navidcy** [comment]
Did you create the `data` and `movies` directories as instructed in the readme?

**Comment by navidcy** [comment]
I've included the `movies` and `data` directories as part of the repository now. Please delete the clone of the repository and try installing again following the instructions in the Readme. Let me know if there is still an issue.

**Comment by navidcy** [comment]
All good @karimrida?

**Comment by karimrida** [comment]
@navidcy Yes! I just got it to work now. I had an issue with how Julia was installed in the terminal, but now it is fixed and the code is working perfectly.  Thank you so much for your help!
